export type ReduxActions =
  | "USER_PROFILE_FETCH_SUCCESS"
  | "USER_PROFILE_FETCH"
  | "USER_PROFILE_FETCH_ERROR"
  | "USER_DATA_FETCH_SUCCESS"
  | "USER_DATA_FETCH"
  | "USER_DATA_FETCH_ERROR"
  | "USER_JOB_FETCH"
  | "USER_JOB_FETCH_SUCCESS"
  | "USER_JOB_FETCH_ERROR"
  | "USER_RESPOND_FETCH"
  | "USER_RESPOND_FETCH_SUCCESS"
  | "USER_RESPOND_FETCH_ERROR"
  | "USER_JOB_DELETE"
  | "USER_JOB_DELETE_SUCCESS"
  | "USER_JOB_DELETE_ERROR"
  | "JOB_FETCH"
  | "JOB_FETCH_SUCCESS"
  | "JOB_FETCH_ERROR"
  | "JOB_RESPOND_ADD_SUCCESS"
  | "JOB_RESPOND_ADD_ERROR"
  | "JOB_RESPOND_ADD"
  | "JOB_RESPOND_DELETE_SUCCESS"
  | "JOB_RESPOND_DELETE_ERROR"
  | "JOB_RESPOND_DELETE"
  | "ACCOUNT_AUTH"
  | "ACCOUNT_AUTH_ERROR"
  | "ACCOUNT_AUTH_SUCCESS"
  | "ACCOUNT_LOGOUT"
  | "ACCOUNT_TOKEN_CHECK"
  | "ACCOUNT_TOKEN_CHECK_SUCCESS"
  | "ACCOUNT_TOKEN_CHECK_ERROR";

export type ActionStatus = "IDLE" | "LOADING" | "ERROR" | "SUCCESS";

export interface IReduxAction<T = any> {
  type: ReduxActions;
  payload?: T;
}
