export type ReduxActions =
  | "USER_ACCOUNT_AUTH"
  | "USER_ACCOUNT_AUTH_ERROR"
  | "USER_ACCOUNT_AUTH_SUCCESS"
  | "USER_ACCOUNT_LOGOUT"
  | "USER_ACCOUNT_TOKEN_CHECK"
  | "USER_ACCOUNT_TOKEN_CHECK_SUCCESS"
  | "USER_ACCOUNT_TOKEN_CHECK_ERROR"
  | "USER_ACCOUNT_FETCH"
  | "USER_ACCOUNT_FETCH_ERROR"
  | "USER_ACCOUNT_FETCH_SUCCESS"
  | "USER_PROFILE_FETCH_SUCCESS"
  | "USER_PROFILE_FETCH"
  | "USER_PROFILE_FETCH_ERROR"
  | "USER_DATA_FETCH_SUCCESS"
  | "USER_DATA_FETCH"
  | "USER_DATA_FETCH_ERROR"
  | "USER_JOBS_FETCH"
  | "USER_JOBS_FETCH_SUCCESS"
  | "USER_JOBS_FETCH_ERROR"
  | "USER_RESPONDS_FETCH"
  | "USER_RESPONDS_FETCH_SUCCESS"
  | "USER_RESPONDS_FETCH_ERROR"
  | "USER_JOB_DELETE"
  | "USER_JOB_DELETE_SUCCESS"
  | "USER_JOB_DELETE_ERROR"
  | "USER_JOB_ADD"
  | "USER_JOB_ADD_SUCCESS"
  | "USER_JOB_ADD_ERROR"
  | "USER_RESPOND_ADD_SUCCESS"
  | "USER_RESPOND_ADD_ERROR"
  | "USER_RESPOND_ADD"
  | "USER_RESPOND_DELETE_SUCCESS"
  | "USER_RESPOND_DELETE_ERROR"
  | "USER_RESPOND_DELETE"
  | "USER_RESPOND_STATUS_CHANGE_SUCCESS"
  | "USER_RESPOND_STATUS_CHANGE_ERROR"
  | "USER_RESPOND_STATUS_CHANGE"
  | "JOB_GET_SECRET_SUCCESS"
  | "JOB_GET_SECRET_ERROR"
  | "JOB_GET_SECRET"
  | "JOB_LIST_FETCH"
  | "JOB_LIST_FETCH_SUCCESS"
  | "JOB_LIST_FETCH_ERROR";

export type ActionType = "JOB_FETCH" | "JOB_FETCH_SUCCESS" | "JOB_FETCH_ERROR";

export type ActionStatus = "IDLE" | "LOADING" | "ERROR" | "SUCCESS";

// export type EntityName = "account" | "data" | ""

export interface IReduxAction<T = any> {
  type: ReduxActions & ActionType;
  entityName: string;
  payload?: T;
}
